### ISSUE TITLE
Support new Canvas font properties

### ISSUE THREAD

**Issue by Awendel** [glideapps/canvas-hypertxt#2]
Chrome has recently released new font properties for the Canvas API:

https://developer.chrome.com/blog/canvas2d/

Important aspects:
- letter-spacing
- word-spacing
- font-style 

all these would affect the line breaking algorithm

.measureText() does incorporate these already, so would be great to add it to your library

**Comment by jassmith** [comment]
Im not sure why these wouldn't work. This library takes in the ctx "as is" and uses it to perform measurement.

**Comment by Awendel** [comment]
My bad, read the example code wrong - yes by passing on ctx object this should be taken care of.
One could think about offering a polyfill for Firefox etc. - will probably be a while before it lands.
letterSpacing and wordSpacing shouldn't be too hard to compute based on how many displayChars and wordSeperators are inside a given line.
I understand of course if its out of scope for this lib to polyfill canvas behaviour
